"""Features subpackage — Numba-jitted waveform feature kernels."""
from spike_discrim.features.extraction import build_feature_matrix
from spike_discrim.features.core_features import (
    OP_COUNTS,
    SCALAR_FEATURE_NAMES,
    TEMPORAL_MAD_FEATURE_PREFIX,
    amplitude,
    first_derivative,
    second_derivative,
    absolute_window_sum,
    short_window_energy,
    teager_energy,
    batch_amplitude,
    batch_first_derivative,
    batch_second_derivative,
    batch_absolute_window_sum,
    batch_short_window_energy,
    batch_teager_energy,
    batch_extract_scalar_features,
    batch_estimate_snippet_edge_noise_mad,
    batch_extract_temporal_mad_features,
    build_temporal_mad_feature_names,
    compute_temporal_window_bounds,
    extract_temporal_mad_features,
)
from spike_discrim.features.event_features import (
    EVENT_FEATURE_NAMES,
    N_EVENT_FEATURES,
    batch_event_features,
    trough_amplitude,
    peak_amplitude,
    trough_to_peak_time,
    half_width,
    biphasic_ratio,
    baseline_rms,
    zero_crossing_count,
)

__all__ = [
    "build_feature_matrix",
    "OP_COUNTS",
    "SCALAR_FEATURE_NAMES",
    "TEMPORAL_MAD_FEATURE_PREFIX",
    "EVENT_FEATURE_NAMES",
    "N_EVENT_FEATURES",
    "amplitude", "first_derivative", "second_derivative",
    "absolute_window_sum", "short_window_energy", "teager_energy",
    "batch_amplitude", "batch_first_derivative", "batch_second_derivative",
    "batch_absolute_window_sum", "batch_short_window_energy", "batch_teager_energy",
    "batch_extract_scalar_features",
    "batch_estimate_snippet_edge_noise_mad",
    "batch_extract_temporal_mad_features",
    "build_temporal_mad_feature_names",
    "compute_temporal_window_bounds",
    "extract_temporal_mad_features",
    "batch_event_features",
    "trough_amplitude", "peak_amplitude", "trough_to_peak_time",
    "half_width", "biphasic_ratio", "baseline_rms", "zero_crossing_count",
]
